### ISSUE TITLE
Modularize config

### ISSUE THREAD

**Issue by schuderer** [schuderer/mllaunchpad#28]
Currently, the config file is monolithic, meaning that the complete config is per model. Make it possible to include subdictionaries/subobjects of the config (like some/all datasources). 

This will avoid the potential problem that if for example many models use the same database and its location changes, all configs have to be updated. I would still make it non-mandatory to split up tho config, because when starting out, it’s *much* less hassle to just have one config. 

Possible approach (safe?): https://stackoverflow.com/questions/528281/how-can-i-include-a-yaml-file-inside-another#15437697

Suggestion:
* In the `my_config.yml` file, one should be able to use `!include <filename>` at the position where we include a dict from another yaml file, and the `!include ...` in the config object gets replaced by this object.
* If relative paths are used, they should be relative to the location of the main config-yaml-file (we can use `os.path` to get path to file). Relative paths should NOT be relative to the current working directory. (yes I know, also need to change this for models, raml, etc. -- different issue :))

Consider this example structure of yml files:

```
/home/
  my_user/
    my_model/
        my_config.yml
        country_lookups.yml
    shared/
        dbms.yml
        local_model_store.yml
```

with these file contents:

`/home/my_user/my_model/my_config.yml`:
```yaml
dbms: !include ../shared/dbms.yml

datasources:
    country_lookups: !include country_lookups.yml  # also a relative include
    petals:
        type: csv
        path: ./iris_train.csv
        expires: 0
        options: {}
        tags: train

model_store: !include ../shared/model_store_local.yml
```

`/home/my_user/shared/dbms.yml`:
```yaml
xob10:
    type: oracle
    host: host.example.com
    port: 1521
    user_var: XOB10_USER
    password_var: XOB10_PW
    service_name: servicename.example.com
    options: {}
```

`/home/my_user/my_model/country_lookups.yml`:
```yaml
type: dbms.xob10
query: SELECT LONG_NAME FROM COUNTRIES WHERE SHORT_NAME :id
expires: -1
options: {}
tags: train, test, predict  # todo: make it possible to overrule them in `model:`
```

`/home/my_user/shared/model_store_local.yml`:
```yaml
location: /mounts/nfs/linux393/model_store
```

When reading in the main `my_config.yml`, the result should be a config structure that is equivalent to the following structure:

```yaml
dbms:
  xob10:
    type: oracle
    host: host.example.com
    port: 1521
    user_var: XOB10_USER
    password_var: XOB10_PW
    service_name: servicename.example.com
    options: {}

datasources:
    country_lookups:
        type: dbms.xob10
        query: SELECT LONG_NAME FROM COUNTRIES WHERE SHORT_NAME :id
        expires: -1
        options: {}
        tags: train, test, predict
    petals:
        type: csv  # uses , as separators and . as decimal point
        path: ./iris_train.csv
        expires: 0
        options: {}
        tags: train

model_store:
  location: /mounts/nfs/linux393/model_store
```
